authentication/urls.py
from django.urls import path, include
from django.conf.urls import handler404, handler500
from .views import index, course_list, course_grid, course_sidebar, course_details, blog, blog_details, about, cart, checkout, contact, error, \
    instructor_details, instructor, product, shop, sign_in, sign_up, site, wishlist, add_instructor, user_logout, student, appointment

app_name = 'authentication'

urlpatterns = [
    path('', index, name='index'),
    path('course-list', course_list, name='course-list'),
    path('course-grid', course_grid, name='course-grid'),
    path('course-sidebar', course_sidebar, name='course-sidebar'),
    path('course-details', course_details, name='course-details'),
    path('blog', blog, name='blog'),
    path('blog-details', blog_details, name='blog-details'),
    path('about', about, name='about'),
    path('cart', cart, name='cart'),
    path('checkout', checkout, name='checkout'),
    path('contact', contact, name='contact'),
    path('error', error, name='error'),
    path('instructor-details/<int:pk>', instructor_details, name='instructor-details'),
    path('instructor', instructor, name='instructor'),
    path('product', product, name='product'),
    path('shop', shop, name='shop'),
    path('sign-in', sign_in, name='sign-in'),
    path('sign-up', sign_up, name='sign-up'),
    path('site', site, name='site'),
    path('wishlist', wishlist, name='wishlist'),
    path('add-instructor', add_instructor, name='add-instructor'),
    path('logout', user_logout, name='logout'),
    path('student', student, name='student'),
    path('appointment', appointment, name='appointment'),
]

handler404 = error

brainbox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
]

event/urls.py
from django.urls import path, include
from django.conf.urls import handler404, handler500
from .views import event_details, event, add_event, event_payment, verify_event_payment

app_name = 'event'

urlpatterns = [
    path('', event, name='event'),
    path('add-event', add_event, name='add-event'),
    path('event-details/<int:pk>', event_details, name='event-details'),
    path('event-payment/<int:pk>', event_payment, name='event-payment'),
    path('verify/<str:ref_id>', verify_event_payment, name='verify-event-payment')
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cloudinary.models import CloudinaryField
from django.core.validators import RegexValidator

from .managers import CustomUserManager

# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=50, null=True)
    # avatar = models.ImageField(null=True, upload_to='profile/')
    avatar = CloudinaryField('profile', null=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    middle_name = models.CharField(max_length=15, null=True)
    phone = models.CharField(max_length=15, unique=True)
    status = models.BooleanField(default=True)
    address = models.TextField(null=True)
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    @property
    def full_name(self):
        return self.get_full_name()

    def get_complete_name(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'

    def __str__(self):
        return self.email


class Tutor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.user.email


class Appointment(models.Model):
    APPOINTMENT_STATUS = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Done', 'Done'),
        ('Cancelled', 'Cancelled')
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    subject = models.TextField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, default='Pending', null=True, blank=True)
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)

authentication/forms.py
from django import forms
from cloudinary.forms import CloudinaryFileField
from .models import Appointment, User

class UserCreationForm(forms.ModelForm):
    confirm_password = forms.CharField(label='Confirm Password', required=True)
    address = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'phone', 'address', 'password', 'confirm_password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            msg = "Passwords do not match"
            self.add_error('password', msg)


class LoginForm(forms.Form):
    email_or_phone = forms.CharField(label='Email or Phone', required=True)
    password = forms.CharField(required=True)


class TutorCreationForm(forms.ModelForm):
    confirm_password = forms.CharField(label='Confirm Password', required=True)
    avatar = forms.ImageField(label='Upload Image', required=False)
    description = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'phone', 'password', 'confirm_password', 'description', 'avatar']
        image = CloudinaryFileField(
            options = { 
                'tags': "directly_uploaded",
                'crop': 'limit', 'width': 250, 'height': 250,
                'eager': [{ 'crop': 'fill', 'width': 150, 'height': 100 }]
        })

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            msg = "Passwords do not match"
            self.add_error('password', msg)


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        read_only_fields = ['status', 'time_created', 'date_created', 'user', 'name', 'email']
        fields = '__all__'

authentication/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.template import loader

from django.contrib.auth.models import Group
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages

from .forms import AppointmentForm, LoginForm, TutorCreationForm, UserCreationForm
from .models import Appointment, Tutor, User
from .utils import admin_check

# Create your views here.
def index(request):
    template = loader.get_template('authentication/index.html')
    instructors = Tutor.objects.all()
    context = {
        'instructors':instructors
    }
    return HttpResponse(template.render(context, request))

@login_required()
def course_list(request):
    template = loader.get_template('authentication/course-list.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


@login_required()
def course_grid(request):
    template = loader.get_template('authentication/course-grid.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


@login_required()
def course_sidebar(request):
    template = loader.get_template('authentication/course-sidebar.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


@login_required()
def course_details(request):
    template = loader.get_template('authentication/course-details.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def blog(request):
    template = loader.get_template('authentication/blog.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def blog_details(request):
    template = loader.get_template('authentication/blog-details.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def about(request):
    template = loader.get_template('authentication/about.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def cart(request):
    template = loader.get_template('authentication/cart.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def checkout(request):
    template = loader.get_template('authentication/checkout.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def contact(request):
    template = loader.get_template('authentication/contact.html')
    context = {}
    form = AppointmentForm(request.POST or None)
    print(form.errors)
    print(form.is_valid())
    if form.is_valid():
        appointment = form.save()
        if request.user.is_authenticated:
            appointment.user = request.user
        appointment.save()
        messages.success(request, "Appointment created successfully.")
        return redirect("authentication:index")
    context['form']= form
    return HttpResponse(template.render(context, request))


def error(request, exception):
    template = loader.get_template('authentication/error.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def instructor_details(request, pk):
    template = loader.get_template('authentication/instructor-details.html')
    tutor = Tutor.objects.get(id=pk)
    # user = User.objects.get(id=pk)
    context = {
        'tutor': tutor
    }
    return HttpResponse(template.render(context, request))


def instructor(request):
    template = loader.get_template('authentication/instructor.html')
    instructors = Tutor.objects.all()
    context = {
        'instructors': instructors
    }
    return HttpResponse(template.render(context, request))


def product(request):
    template = loader.get_template('authentication/product.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def shop(request):
    template = loader.get_template('authentication/shop.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def sign_in(request):
    template = loader.get_template('authentication/sign-in.html')
    context = {}
    form = LoginForm(request.POST or None)
    if form.is_valid():
        email_or_phone = form.cleaned_data.get('email_or_phone')
        password = form.cleaned_data.get('password')
        try:
            user = User.objects.get(Q(email__iexact=email_or_phone)|Q(phone__iexact=email_or_phone))
            if user.check_password(password):
                next = request.GET.get('next')
                login(request, user)
                messages.success(request, "Login successful.")
                if next is not None:
                    return redirect(next)
                return redirect("authentication:index")
            else:
                messages.error(request,"Incorrect password")
        except User.DoesNotExist:
            messages.error(request,"Invalid email or phone")
    context['form']= form
    return HttpResponse(template.render(context, request))


def sign_up(request):
    template = loader.get_template('authentication/sign-up.html')
    context = {}
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        password = form.cleaned_data.pop('password')
        user = form.save()
        group, _ = Group.objects.get_or_create(name='student')
        user.groups.add(group)
        user.set_password(password)
        user.save()
        login(request, user)
        messages.success(request, "Registration successful.")
        return redirect("authentication:index")
    context['form']= form
    return HttpResponse(template.render(context, request))


def site(request):
    template = loader.get_template('authentication/site.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def wishlist(request):
    template = loader.get_template('authentication/wishlist.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


@user_passes_test(admin_check)
def add_instructor(request):
    template = loader.get_template('authentication/add-instructor.html')
    context = {}
    form = TutorCreationForm(request.POST, request.FILES)
    print('data', request.POST)
    print('file', request.FILES)
    if form.is_valid():
        description = form.cleaned_data.get('description')
        password = form.cleaned_data.pop('password')
        user = form.save()
        group, _ = Group.objects.get_or_create(name='instructor')
        user.groups.add(group)
        user.set_password(password)
        user.save()
        Tutor.objects.create(user=user, description=description)
        messages.success(request, "Tutor created successful.")
        return redirect("authentication:instructor")
    context['form']= form
    return HttpResponse(template.render(context, request))


def user_logout(request):
    logout(request)
    return redirect('authentication:index')


@user_passes_test(admin_check)
def student(request):
    template = loader.get_template('authentication/student.html')
    students = User.objects.filter(groups__name='student')
    paginator = Paginator(students, 10) # Show 25 news per page.
    page_number = request.GET.get('page')
    students = paginator.get_page(page_number)
    context = {
        'students': students
    }
    return HttpResponse(template.render(context, request))


# @user_passes_test(admin_check)
# def add_instructor(request):
#     template = loader.get_template('authentication/add-instructor.html')
#     context = {}
#     form = TutorCreationForm(request.POST or None)
#     if form.is_valid():
#         description = form.cleaned_data.get('description')
#         password = form.cleaned_data.pop('password')
#         user = form.save()
#         group, _ = Group.objects.get_or_create(name='instructor')
#         user.groups.add(group)
#         user.set_password(password)
#         user.save()
#         Tutor.objects.create(user=user, description=description)
#         messages.success(request, "Tutor created successful.")
#         return redirect("authentication:instructor")
#     context['form']= form
#     return HttpResponse(template.render(context, request))


@user_passes_test(admin_check)
def appointment(request):
    template = loader.get_template('authentication/appointment.html')
    appointments = Appointment.objects.all()
    paginator = Paginator(appointments, 10) # Show 25 news per page.
    page_number = request.GET.get('page')
    appointments = paginator.get_page(page_number)
    context = {
        'appointments': appointments
    }
    return HttpResponse(template.render(context, request))

authentication/templates/authentication/error.html
{% extends "base.html" %}
{% load static %}
   {% block body %}
      <main>

         <!-- error area start -->
         <section class="error__area pt-200 pb-200">
            <div class="container">
               <div class="row">
                  <div class="col-xxl-8 offset-xxl-2 col-xl-8 offset-xl-2 col-lg-10 offset-lg-1">
                     <div class="error__item text-center">
                        <div class="error__thumb mb-45">
                           <img src="{% static 'authentication/img/error/error.png' %}" alt="">
                        </div>
                        <div class="error__content">
                           <h3 class="error__title">Page Not Found!</h3>
                           <p>Please try searching for some other page.</p>
                           <a href="{% url 'authentication:index' %}" class="e-btn e-btn-3 e-btn-4">Back To Home</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- error area end -->

      </main>
      {% endblock %}

authentication/templates/authentication/instructor.html
{% extends "base.html" %}
{% load static %}
{% load user_group %}
   {% block body %}
      <main>

         <!-- page title area start -->
         <section class="page__title-area page__title-height page__title-overlay d-flex align-items-center" data-background="{% static 'authentication/img/page-title/page-title.jpg' %}">
            <div class="container">
               <div class="row">
                  <div class="col-xxl-12">
                     <div class="page__title-wrapper mt-110">
                        <h3 class="page__title">Instructor</h3>                         
                        <nav aria-label="breadcrumb">
                           <ol class="breadcrumb">
                              <li class="breadcrumb-item"><a href="{% url 'authentication:index' %}">Home</a></li>
                              <li class="breadcrumb-item active" aria-current="page">Instructor</li>
                              {% if request.user|has_group:"admin" %}
                                 <li class="breadcrumb-item"><a href="{% url 'authentication:add-instructor' %}">Add Instructor</a></li>
                              {% endif %}
                           </ol>
                        </nav>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- page title area end -->

         <!-- teacher area start -->
         <section class="teacher__area pt-115 pb-110">
            <div class="container">
               <div class="row">
                  <div class="col-xxl-6 offset-xxl-3">
                     <div class="section__title-wrapper text-center mb-60">
                        <h2 class="section__title">Our Most <br>
                           Popular <span class="yellow-bg"> Teachers <img src="{% static 'authentication/img/shape/yellow-bg-2.png' %}" alt="">  </span> <br>
                        </h2>
                        <p>You don't have to struggle alone, you've got our assistance and help.</p>
                     </div>
                  </div>
               </div>
               <div class="row">
                  {% for instructor in instructors %}
                     <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                        <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                           <div class="teacher__thumb w-img fix">
                              <a href="{% url 'authentication:instructor-details' instructor.id %}">
                                 <img src="{{ instructor.user.avatar.url }}" alt="Instructor Image">
                              </a>
                           </div>
                           <div class="teacher__content">
                              <h3 class="teacher__title">{{ instructor.user.first_name|title }} {{ instructor.user.last_name|title }}</h3> 
                              <span>{{ instructor.description }}</span>

                              <div class="teacher__social">
                                 <ul>
                                    <li><a href="#"><i class="social_facebook"></i></a></li>
                                    <li><a href="#"><i class="social_twitter"></i></a></li>
                                    <li><a href="#"><i class="social_vimeo"></i></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  {% endfor %}
                  <!-- <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacger-1.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Lillian Walsh,</h3> 
                           <span> CO Founder</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacher-2.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Kelly Franklin,</h3> 
                           <span>Desginer</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacher-3.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Hilary Ouse,</h3> 
                           <span>Markater</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacher-5.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Lillian Walsh,</h3> 
                           <span>CO Founder</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacher-4.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Shahnewaz,</h3> 
                           <span>Web Developer</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6">
                     <div class="teacher__item text-center grey-bg-5 transition-3 mb-30">
                        <div class="teacher__thumb w-img fix">
                           <a href="#">
                              <img src="{% static 'authentication/img/teacher/teacher-6.jpg' %}" alt="">
                           </a>
                        </div>
                        <div class="teacher__content">
                           <h3 class="teacher__title">Nicola Tesla,</h3> 
                           <span>Engineer</span>

                           <div class="teacher__social">
                              <ul>
                                 <li><a href="#"><i class="social_facebook"></i></a></li>
                                 <li><a href="#"><i class="social_twitter"></i></a></li>
                                 <li><a href="#"><i class="social_vimeo"></i></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div> -->
               </div>
            </div>
         </section>
         <!-- teacher area end -->

         <!-- banner area start -->
         <section class="banner__area pb-80">
            <div class="container">
               <div class="row">
                  <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6">
                     <div class="banner__item p-relative mb-40" data-background="{% static 'authentication/img/banner/banner-bg-1.jpg' %}">
                        <div class="banner__content">
                           <span>Free</span>
                           <h3 class="banner__title">
                              <a href="{% url 'authentication:course-details' %}">Germany Foundation <br> Document</a>
                           </h3>
                           <a href="{% url 'authentication:course-grid' %}" class="e-btn e-btn-2">View Courses</a>
                        </div>
                        <div class="banner__thumb d-none d-sm-block d-md-none d-lg-block">
                           <img src="{% static 'authentication/img/banner/banner-img-1.png' %}" alt="">
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6">
                     <div class="banner__item p-relative mb-40" data-background="{% static 'authentication/img/banner/banner-bg-2.jpg' %}">
                        <div class="banner__content">
                           <span class="orange">new</span>
                           <h3 class="banner__title">
                              <a href="{% url 'authentication:course-details' %}">Online Courses <br>From Eduka University</a>
                           </h3>
                           <a href="{% url 'authentication:course-grid' %}" class="e-btn e-btn-2">Find Out More</a>
                        </div>
                        <div class="banner__thumb banner__thumb-2 d-none d-sm-block d-md-none d-lg-block">
                           <img src="{% static 'authentication/img/banner/banner-img-2.png' %}" alt="">
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- banner area end -->
      </main>
   {% endblock %}