authentication/urls.py
from django.urls import path, include
from django.conf.urls import handler404, handler500
from .views import index, course_list, course_grid, course_sidebar, course_details, blog, blog_details, about, cart, checkout, contact, error, \
    instructor_details, instructor, product, shop, sign_in, sign_up, site, wishlist, add_instructor, user_logout, student, appointment

app_name = 'authentication'

urlpatterns = [
    path('', index, name='index'),
    path('course-list', course_list, name='course-list'),
    path('course-grid', course_grid, name='course-grid'),
    path('course-sidebar', course_sidebar, name='course-sidebar'),
    path('course-details', course_details, name='course-details'),
    path('blog', blog, name='blog'),
    path('blog-details', blog_details, name='blog-details'),
    path('about', about, name='about'),
    path('cart', cart, name='cart'),
    path('checkout', checkout, name='checkout'),
    path('contact', contact, name='contact'),
    path('error', error, name='error'),
    path('instructor-details/<int:pk>', instructor_details, name='instructor-details'),
    path('instructor', instructor, name='instructor'),
    path('product', product, name='product'),
    path('shop', shop, name='shop'),
    path('sign-in', sign_in, name='sign-in'),
    path('sign-up', sign_up, name='sign-up'),
    path('site', site, name='site'),
    path('wishlist', wishlist, name='wishlist'),
    path('add-instructor', add_instructor, name='add-instructor'),
    path('logout', user_logout, name='logout'),
    path('student', student, name='student'),
    path('appointment', appointment, name='appointment'),
]

handler404 = error

brainbox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
]

event/urls.py
from django.urls import path, include
from django.conf.urls import handler404, handler500
from .views import event_details, event, add_event, event_payment, verify_event_payment

app_name = 'event'

urlpatterns = [
    path('', event, name='event'),
    path('add-event', add_event, name='add-event'),
    path('event-details/<int:pk>', event_details, name='event-details'),
    path('event-payment/<int:pk>', event_payment, name='event-payment'),
    path('verify/<str:ref_id>', verify_event_payment, name='verify-event-payment')
]

event/models.py
from django.db import models

from authentication.models import User, Tutor

# Create your models here.
class Event(models.Model):
    EVENT_STATUS = (
        ('On-Going', 'On-Going'),
        ('Ended', 'Ended'),
        ('Upcoming', 'Upcoming'),
        ('Cancelled', 'Cancelled')
    )
    topic = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField()
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='event_created_by')
    tutors = models.ManyToManyField(Tutor)
    participants = models.ManyToManyField(User, blank=True)
    event_type = models.CharField(max_length=50)
    event_date = models.DateField()
    event_time = models.TimeField()
    duration_in_hours = models.IntegerField()
    status = models.CharField(max_length=20, choices=EVENT_STATUS, default='Upcoming')
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, null=True, blank=True)
    location = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.topic


# Create your models here.
class Transaction(models.Model):
    TRANSACTION_TYPE = (
        ('event','event'),
    )
    amount = models.FloatField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True, blank=True)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE)
    transfer_code = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    reference = models.CharField(max_length=20, null=True, blank=True)
    authorization_code = models.CharField(max_length=20, null=True, blank=True)
    paystack_ref = models.CharField(max_length=20, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.id)


class WebhookTransaction(models.Model):
    event = models.CharField(max_length=50, null=True, blank=True)
    transfer_code = models.CharField(max_length=50, null=True, blank=True)
    amount = models.FloatField(null=True, blank=True)
    transfer_recipient = models.CharField(max_length=50, null=True, blank=True)
    reference = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True)
    time_created = models.TimeField(auto_now_add=True, null=True, blank=True)
    date_created = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.id)

event/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        read_only_fields = ['created_by', 'time_created', 'date_created', 'last_updated']
        fields = '__all__'

event/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse
from django.template import loader
from django.core.paginator import Paginator
from django.contrib import messages
from event.helpers import generate_transaction_reference

from event.utils import initialize_transaction, verify_transaction

from .forms import EventForm

from .models import Event, Transaction

# Create your views here.
def event(request):
    template = loader.get_template('event/event.html')
    events = Event.objects.all()
    paginator = Paginator(events, 10) # Show 25 news per page.
    page_number = request.GET.get('page')
    events = paginator.get_page(page_number)
    context = {
        'events': events
    }
    return HttpResponse(template.render(context, request))


def add_event(request):
    template = loader.get_template('event/add-event.html')
    context = {}
    print(request.POST)
    form = EventForm(request.POST or None)
    print(form.is_valid)
    print(form.errors)
    if form.is_valid():
        event = form.save()
        messages.success(request, "Event created successful.")
        return redirect("event:event")
    context['form']= form
    return HttpResponse(template.render(context, request))

    
def event_details(request, pk):
    template = loader.get_template('event/event-details.html')
    event = Event.objects.get(id=pk)
    context = {
        'event': event
    }
    return HttpResponse(template.render(context, request))


def event_payment(request, pk):
    try:
        event = Event.objects.get(id=pk)
        if event.status not in ['Upcoming', 'On-Going']:
            messages.error(request, "Event is not available")
            return redirect(reverse('event:event-details', kwargs={"pk": event.id}))
        else:
            amount = event.price
            reference = generate_transaction_reference('event')
            paystact_init = initialize_transaction(request.user.email, amount, reference)
            if paystact_init is not None:
                Transaction.objects.create(
                    amount = amount,
                    user = request.user,
                    event = event,
                    transaction_type = 'event',
                    status = 'pending',
                    reference = reference,
                    paystack_ref = paystact_init['data']['reference']
                )
                return redirect(paystact_init['data']['authorization_url'])
            else:
                messages.error(request, "Transaction failed")
                return redirect(reverse('event:event-details', kwargs={"pk": event.id}))
    except Event.DoesNotExist:
        messages.error(request, "Event does not exist")
        return redirect("event:event")


def verify_event_payment(request, ref_id):
    try:
        txn = Transaction.objects.get(reference=ref_id)
        verify_txn = verify_transaction(ref_id)
        if verify_txn is not None:
            if verify_txn['data']['status'] == 'success':
                txn.status = 'success'
                txn.authorization_code = verify_txn['data']['authorization']['authorization_code']
                txn.save()
                return redirect("event:event")
            else:
                return redirect("event:event")
        else:
            return redirect("event:event")
    except Transaction.DoesNotExist:
        return redirect("event:event")

event/templates/event/event-details.html
{% extends "base.html" %}
{% load static %}
   {% block body %}
      <main>

         <!-- page title area start -->
         <section class="page__title-area pt-120">
            <div class="page__title-shape">
               <img class="page-title-shape-5 d-none d-sm-block" src="{% static 'authentication/img/page-title/page-title-shape-1.png' %}" alt="">
               <img class="page-title-shape-6" src="{% static 'authentication/img/page-title/page-title-shape-2.png' %}" alt="">
               <img class="page-title-shape-7" src="{% static 'authentication/img/page-title/page-title-shape-4.png' %}" alt="">
               <img class="page-title-shape-8" src="{% static 'authentication/img/page-title/page-title-shape-5.png' %}" alt="">
            </div>
            <div class="container">
               <div class="row">
                  <div class="col-xxl-9 col-xl-8">
                     <div class="page__title-content mb-25 pr-40">
                        <div class="page__title-breadcrumb">                            
                            <nav aria-label="breadcrumb">
                              <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'authentication:index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'authentication:course-grid' %}">Event</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{ event.topic }}</li>
                              </ol>
                            </nav>
                        </div>
                        <span class="page__title-pre purple-bg">{{ event.event_type }}</span>
                        <h5 class="page__title-3">{{ event.topic }}</h5>
                     </div>
                     <div class="course__meta-2 d-sm-flex mb-30">
                        <div class="course__teacher-3 d-flex align-items-center mr-70 mb-30">
                           {% for tutor in event.tutors.all %}
                           <div class="course__teacher-thumb-3 mr-15">
                              <img src="{{ tutor.user.avatar.url }}" alt="">
                           </div>
                           <div class="course__teacher-info-3">
                              <h5>Teacher</h5>
                              <p><a href="{% url 'authentication:instructor-details' tutor.user.id %}">{{ tutor.user.first_name }} {{ tutor.user.last_name }}</a></p>
                           </div>
                           {% endfor %}
                        </div>
                        <div class="course__update mr-80 mb-30">
                           <h5>Duration:</h5>
                           <p>{{ event.duration_in_hours }} hours</p>
                        </div>
                        <div class="course__update mb-30">
                           <h5>Location:</h5>
                           <p>{{ event.location }}</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- page title area end -->

         <!-- event details area start -->
         <section class="event__area pb-110">
            <div class="container">
               <div class="row">
                  <div class="col-xxl-8 col-xl-8 col-lg-8">
                     <div class="events__wrapper">
                        <!-- <div class="events__thumb mb-35 w-img">
                           <img src="{% static 'authentication/img/events/event-1.jpg' %}" alt="">
                        </div> -->
                        <div class="events__details mb-35">
                           <h3>Description</h3>
                           <p>{{ event.description }}</p>
                        </div>
                        <!-- <div class="events__allow mb-40">
                           <h3>This event will allow participants to:</h3>
                           <ul>
                              <li><i class="fal fa-check"></i> Business's managers, leaders</li>
                              <li><i class="fal fa-check"></i> Downloadable lectures, code and design assets for all projects</li>
                              <li><i class="fal fa-check"></i> Anyone who is finding a chance to get the promotion</li>
                           </ul>
                        </div> -->
                        <div class="events__tag">
                           <span><i class="fal fa-tag"></i></span>
                           <b>Event Date: {{ event.event_date }}</b><br>
                           <span><i class="fal fa-tag"></i></span>
                           <b>Event Time: {{ event.event_time }}</b><br>
                           <span><i class="fal fa-tag"></i></span>
                           <b>Duration: {{ event.duration_in_hours }} hours</b>
                           <!-- <a href="#">Big data,  </a>
                           <a href="#">Data analysis,</a>
                           <a href="#">Data modeling</a> -->
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-4 col-xl-4 col-lg-4">
                     <div class="events__sidebar pl-70">
                        <div class="events__sidebar-widget white-bg mb-20">
                           <div class="events__sidebar-shape">
                              <img class="events-sidebar-img-2" src="{% static 'authentication/img/events/event-shape-2.png' %}" alt="">
                              <img class="events-sidebar-img-3" src="{% static 'authentication/img/events/event-shape-3.png' %}" alt="">
                           </div>
                           <div class="events__info">
                              <div class="events__info-meta mb-25 d-flex align-items-center justify-content-between">
                                 <div class="events__info-price">
                                    <h5>#{{event.price}}</h5>
                                    <!-- <h5 class="old-price">$142.00</h5> -->
                                 </div>
                                 <!-- <div class="events__info-discount">
                                    <span>68% OFF</span>
                                 </div> -->
                              </div>
                              <div class="events__info-content mb-35">
                                 <ul>
                                    <li class="d-flex align-items-center">
                                       <div class="events__info-icon">
                                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                             <path class="st0" d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z"/>
                                             <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 "/>
                                          </svg>
                                       </div>
                                       <div class="events__info-item">
                                          <h5><span>End: </span>{{ event.event_date }}{{ event.event_time }}</h5>
                                       </div>
                                    </li>
                                    <li class="d-flex align-items-center">
                                       <div class="events__info-icon">
                                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                             <path class="st0" d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z"/>
                                             <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 "/>
                                          </svg>
                                       </div>
                                       <div class="events__info-item">
                                          <h5><span>Time:</span>{{ event.event_time }}</h5>
                                       </div>
                                    </li>
                                    <li class="d-flex align-items-center">
                                       <div class="events__info-icon">
                                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                                             <path class="st0" d="M2,6l6-4.7L14,6v7.3c0,0.7-0.6,1.3-1.3,1.3H3.3c-0.7,0-1.3-0.6-1.3-1.3V6z"/>
                                             <polyline class="st0" points="6,14.7 6,8 10,8 10,14.7 "/>
                                          </svg>
                                       </div>
                                       <div class="events__info-item">
                                          <h5><span>Venue: </span>{{ event.location }}</h5>
                                       </div>
                                    </li>
                                 </ul>
                              </div>
                              <div class="events__join-btn">
                                 {% if event.price > 0 %}
                                    <a href="{% url 'event:event-payment' event.id %}" class="e-btn e-btn-7 w-100">Enroll <i class="far fa-arrow-right"></i></a>
                                 {% else %}
                                    <a href="{% url 'authentication:contact' %}" class="e-btn e-btn-7 w-100">Enroll For Free<i class="far fa-arrow-right"></i></a>
                                 {% endif %}
                              </div>
                           </div>
                        </div>
                        <!-- <div class="events__sidebar-widget white-bg">
                           <div class="events__sponsor">
                              <h3 class="events__sponsor-title">Sponsors</h3>
                              <div class="events__sponsor-thumb mb-35">
                                 <img src="{% static 'authentication/img/events/sponsor-logo.png' %}" alt="">
                              </div>
                              <div class="events__sponsor-info">
                                 <h3>Thomas R. Toe</h3>
                                 <h4>Email: <span><a href="https://themepure.net/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="07747277776875734762637264666b2964686a">[email&#160;protected]</a></span></h4>
                                 <div class="events__social d-xl-flex align-items-center">
                                    <h4>Share:</h4>
                                    <ul>
                                       <li><a href="#" class="fb" ><i class="social_facebook"></i></a></li>
                                       <li><a href="#" class="tw" ><i class="social_twitter"></i></a></li>
                                       <li><a href="#" class="pin" ><i class="social_pinterest"></i></a></li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </div> -->
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- event details area end -->

         <!-- cta area start -->
         <section class="cta__area mb--120">
            <div class="container">
               <div class="cta__inner blue-bg fix">
                  <div class="cta__shape">
                     <img src="{% static 'authentication/img/cta/cta-shape.png' %}" alt="">
                  </div>
                  <div class="row align-items-center">
                     <div class="col-xxl-7 col-xl-7 col-lg-8 col-md-8">
                        <div class="cta__content">
                           <h3 class="cta__title">You can be your own Guiding star with our help</h3>
                        </div>
                     </div>
                     <div class="col-xxl-5 col-xl-5 col-lg-4 col-md-4">
                        <div class="cta__more d-md-flex justify-content-end p-relative z-index-1">
                           <a href="{% url 'authentication:contact' %}" class="e-btn e-btn-white">Get Started</a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- cta area end -->
      </main>
      {% endblock %}